#!/bin/bash

nonce=$(cat /dev/urandom | tr -dc '0-9a-z' | fold -w 256 | head -n 1 | head --bytes 16)
timestamp=$(date +%s)
wskey=$(cat wskey)
secret=$(cat secret)
principalID=$(cat principalID)
principalIDNS=$(cat principalIDNS)
registryID=$(cat registryID)

institution="OHS"
oclc="57639096"

#uri="https://worldcat.org/ih/checkholdings?holdingCode=$institution&oclcNumber=$oclc"

#prehashstring=$(printf '%s\n' "$wskey" "$timestamp" "$nonce" "" "GET" "www.oclc.org" "443" "/wskey" "holdingLibraryCode=$institution" "oclcNumber=$oclc" "")
prehashstring=$(printf '%s\n' "$wskey" "$timestamp" "$nonce" "" "GET" "www.oclc.org" "443" "/wskey" "holdingLibraryCode=$institution" "oclcNumber=$oclc" "")

signature=$(echo "$prehashstring" | openssl dgst -sha256 -hmac "$secret" -binary| sed 's/^.*= //' | base64)
getrequest="https://worldcat.org/ih/checkholdings?holdingLibraryCode=$institution&oclcNumber=$oclc"

echo $prehashstring
# GET https://worldcat.org/ih/checkholdings?holdingCode=OCPSB&oclcNumber=426794447
#
# DELETE https://worldcat.org/ih/data?holdingCode=OCPSB&oclcNumber=426794447&cascade=1 
#
# cascade deletes LHRs as well

curl -v -i -H "Authorization: http://www.worldcat.org/wskey/v2/hmac/v1 clientId=$wskey, timestamp=$timestamp, nonce=$nonce, signature=$signature, principalID=$principalID, principalIDNS=$principalIDNS" $getrequest

